### ISSUE TITLE
Bot API not working?

### ISSUE THREAD

**Issue by ManuXD32** [Revisto/minecraft-telegram-bot#2]
Hi, I'm trying to setup the bot but I get the error that the API token is incorrect, I've double checked it and it seems to be fine.

Mi .env file looks like this
minecraft_server_ip="xxxxxxxxx"
minecraft_server_port="xxxxxxx"
telegram_robot_access_token="xxxxxxxxxxxxxxxxxxxx"

And the error that docker throws is this
2024-07-26 07:04:19,065 - __main__ - INFO - Starting bot
Traceback (most recent call last):
  File "bot.py", line 71, in <module>
    main()
  File "bot.py", line 60, in main
    application = Application.builder().token(Config.TELEGRAM_ACCESS_TOKEN).build()
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_applicationbuilder.py", line 310, in build
    bot: Bot = self._build_ext_bot()  # build a bot
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_applicationbuilder.py", line 272, in _build_ext_bot
    return ExtBot(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 229, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 255, in __init__
    raise InvalidToken("You must pass the token you received from https://t.me/Botfather!")
telegram.error.InvalidToken: You must pass the token you received from https://t.me/Botfather!

**Comment by ManuXD32** [comment]
Solved!
The .env file needs to be inside the mc_bot folder before building.
